### ISSUE TITLE
"_factor not defined" error

### ISSUE THREAD

**Issue by reven** [RobTillaart/BH1750FVI_RT#10]
On an ESP8266 board I get a "_factor not defined" error when compiling the cont_high_res example as follows:

```
/Users/Reven/Documents/Arduino/libraries/BH1750FVI_RT/BH1750FVI.cpp: In constructor 'BH1750FVI::BH1750FVI(uint8_t, uint8_t, uint8_t)':
/Users/Reven/Documents/Arduino/libraries/BH1750FVI_RT/BH1750FVI.cpp:27:3: error: '_factor' was not declared in this scope
   _factor  = BH1750FVI_REFERENCE_TIME;
   ^
exit status 1
```

Looking at the other constructor below, it uses `_sensitivityFactor` instead. Not sure if it's just a typo or if `_factor` is intentional and something else is wrong.

**Comment by RobTillaart** [comment]
Thanks for reporting
Think I missed it during a refactor, a rename will confirm this hypothesis.

Will check it later today.

**Comment by RobTillaart** [comment]
All examples do now compile for ESP32 and UNO - please verify it works for you

**Comment by reven** [comment]
Yes, works perfectly. Thank you!
