### ISSUE TITLE
arduino mega 2560 issue initialising

### ISSUE THREAD

**Issue by gallathan** [RobTillaart/BH1750FVI_RT#17]
hi, cant follow examples and create a variable for the sensor

basically have to declare pointer/static var in setup() AFTER Wire.being is called on a mega, otherwise it hangs

**Comment by RobTillaart** [comment]
Hi, 
Can you post the code or mention the example that fails? 
Can you give more detail what fails?
Does it only fail on a mega?

**Comment by RobTillaart** [comment]
Is this issue still valid, otherwise it can be closed.

**Comment by RobTillaart** [comment]
If the issue is not solved you can reopen the issue, but please provide the answers on the questions above.
